### ISSUE TITLE
Actividad 6 Diseño de libreria para App Escritorio

### ISSUE THREAD

**Issue by Luisangelriverosbautista** [SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-team-ola#1]
[UbitecTrabajo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-team-ola/files/14704279/UbitecTrabajo.pdf)
REPORTE PRACTICA 5

**Comment by GerardoNR** [comment]
19 
cumple con la mayoria de imagenes iformacion,solo que no detallo bien su informacion al implementarla

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
